variable "services_config" {
  type = object({
    service_type = string,
    config       = map(any),
  })

  description = "Configuration as generated by a services module"
}

variable "external_name" {
  description = "Name the cluster will advertise itself as"
}

variable "encryption_password" {
  type        = string
  description = "The password for data encryption in non-external services modes."
  default     = ""
}

variable "ca_certs" {
  description = "Additional CA Certificates to trust (provided concatinated PEMs)"
  default     = ""
}

variable "tls_versions" {
  description = "TLS Versions to support. Supports tls_1_2_tls_1_3, tls_1_2, or tls_1_3 only"
  default     = "tls_1_2_tls_1_3"
}

variable "worker_memory" {
  description = "The number of megabytes to allocate for each terraform run"
  default     = "512"
}

variable "extra_no_proxy" {
  description = "Additional values for no_proxy, specified as comma separated matches against hostnames"
  default     = ""
}

variable "custom_image" {
  description = "The docker image to perform Terraform runs in, rather than the default"
  default     = ""
}

variable "iact_subnet_list" {
  description = "The subnetworks to allow to use the Initial Admin Creation Token API"
  default     = ""
}

variable "iact_subnet_time_limit" {
  description = "The amount of time to allow to use the Initial Admin Creation Token API. Set to 'unlimited' to always allow."
  default     = ""
}

variable "external_vault_addr" {
  default = ""
}

variable "external_vault_role_id" {
  default = ""
}

variable "external_vault_secret_id" {
  default = ""
}

variable "external_vault_path" {
  default = ""
}

variable "external_vault_token_renew" {
  default = ""
}
