name: Pull Request Dispatcher

on:
  issue_comment:
    types:
      - created

jobs:
  slash_command_dispatch:
    name: Slash Command Dispatcher
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@13bc09769d122a64f75aa5037256f6f2d78be8c4 # v4.0.0
        with:
          # The `public_repo` scope is required by this token to create repository_dispatch and workflow_dispatch
          # events on public repositories. The default GITHUB_TOKEN does not support the `public_repo` scope.
          token: ${{ secrets.GH_DISPATCH_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: |
            test
            destroy
            help
          permission: maintain
          issue-type: pull-request
          event-type-suffix: -command
