name: Pull Request Test Handler

on:
  repository_dispatch:
    types:
      - test-command

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
  GOOGLE_ZONE: ${{ secrets.GOOGLE_ZONE }}

jobs:
  public_active_active:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/google-tests.yml@ah/tf-8611-gcp-fdo-3
    secrets: inherit
    name: Public Active/Active
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'public-active-active' }}
    with:
      test_name: Public Active/Active
      module_repository_id: hashicorp/terraform-google-terraform-enterprise
      work_dir: ./tests/public-active-active
      k6_work_dir: ./tests/tfe-load-test
      utility_test: false
      is_replicated_deployment: false
      enable_iact_subnet_list: true
      private_test: false
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      TFC_token_secret_name: PUBLIC_ACTIVE_ACTIVE_TFC_TOKEN

  private_active_active:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/google-tests.yml@ah/tf-8611-gcp-fdo-3
    secrets: inherit
    name: Private Active/Active
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'private-active-active' }}
    with:
      test_name: Private Active/Active
      utility_test: false
      is_replicated_deployment: false
      enable_iact_subnet_list: false
      module_repository_id: hashicorp/terraform-google-terraform-enterprise
      work_dir: ./tests/private-active-active
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      TFC_token_secret_name: PRIVATE_ACTIVE_ACTIVE_TFC_TOKEN
      private_test: true

  private_tcp_active_active:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/google-tests.yml@ah/tf-8611-gcp-fdo-3
    secrets: inherit
    name: Private TCP Active/Active
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'private-tcp-active-active' }}
    with:
      test_name: Private TCP Active/Active
      utility_test: false
      is_replicated_deployment: false
      enable_iact_subnet_list: false
      module_repository_id: hashicorp/terraform-google-terraform-enterprise
      work_dir: ./tests/private-tcp-active-active
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      TFC_token_secret_name: PRIVATE_TCP_ACTIVE_ACTIVE_TFC_TOKEN
      private_test: true

  standalone_external_rhel8_worker:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/google-tests.yml@ah/tf-8611-gcp-fdo-3
    secrets: inherit
    name: Standalone External Rhel8 Worker
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'standalone-external-rhel8-worker' }}
    with:
      test_name: Standalone External Rhel8 Worker
      module_repository_id: hashicorp/terraform-google-terraform-enterprise
      work_dir: ./tests/standalone-external-rhel8-worker
      k6_work_dir: ./tests/tfe-load-test
      private_test: false
      utility_test: false
      is_replicated_deployment: false
      enable_iact_subnet_list: false
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      TFC_token_secret_name: STANDALONE_EXTERNAL_RHEL8_WORKER_TFC_TOKEN
      TFC_workspace_substitution_pattern: 's/terraform {/terraform {\n\
        backend "remote" {\n\
          organization = "terraform-enterprise-modules-test"\n\
          workspaces {\n\
            name = "google-standalone-external-rhel8-worker"\n\
          }\n\
        }\n/'

  standalone_mounted_disk:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/google-tests.yml@ah/tf-8611-gcp-fdo-3
    secrets: inherit
    name: Standalone Mounted Disk
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'standalone-mounted-disk' }}
    with:
      test_name: Standalone Mounted Disk
      module_repository_id: hashicorp/terraform-google-terraform-enterprise
      work_dir: ./tests/standalone-mounted-disk
      k6_work_dir: ./tests/tfe-load-test
      utility_test: false
      is_replicated_deployment: false
      private_test: false
      enable_iact_subnet_list: false
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      TFC_token_secret_name: STANDALONE_MOUNTED_DISK_TFC_TOKEN
      TFC_workspace_substitution_pattern: 's/terraform {/terraform {\n\
        backend "remote" {\n\
          organization = "terraform-enterprise-modules-test"\n\
          workspaces {\n\
            name = "google-standalone-mounted-disk"\n\
          }\n\
        }\n/'

  public_active_active_replicated:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/google-tests.yml@ah/tf-8611-gcp-fdo-3
    secrets: inherit
    name: Public Active/Active
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'public-active-active-replicated' }}
    with:
      test_name: Public Active/Active
      module_repository_id: hashicorp/terraform-google-terraform-enterprise
      work_dir: ./tests/public-active-active
      k6_work_dir: ./tests/tfe-load-test
      utility_test: false
      is_replicated_deployment: true
      enable_iact_subnet_list: true
      private_test: false
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      TFC_token_secret_name: PUBLIC_ACTIVE_ACTIVE_REPLICATED_TFC_TOKEN
      TFC_workspace_substitution_pattern: s/google-public-active-active/google-public-active-active-replicated/

  private_active_active_replicated:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/google-tests.yml@ah/tf-8611-gcp-fdo-3
    secrets: inherit
    name: Private Active/Active
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'private-active-active-replicated'}}
    with:
      test_name: Private Active/Active
      utility_test: false
      is_replicated_deployment: true
      enable_iact_subnet_list: false
      module_repository_id: hashicorp/terraform-google-terraform-enterprise
      work_dir: ./tests/private-active-active
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      TFC_token_secret_name: PRIVATE_ACTIVE_ACTIVE_REPLICATED_TFC_TOKEN
      TFC_workspace_substitution_pattern: s/google-private-active-active/google-private-active-active-replicated/
      private_test: true

  private_tcp_active_active_replicated:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/google-tests.yml@ah/tf-8611-gcp-fdo-3
    secrets: inherit
    name: Private TCP Active/Active
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'private-tcp-active-active-replicated' }}
    with:
      test_name: Private TCP Active/Active
      utility_test: false
      is_replicated_deployment: true
      enable_iact_subnet_list: false
      module_repository_id: hashicorp/terraform-google-terraform-enterprise
      work_dir: ./tests/private-tcp-active-active
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      TFC_token_secret_name: PRIVATE_TCP_ACTIVE_ACTIVE_REPLICATED_TFC_TOKEN
      TFC_workspace_substitution_pattern: s/google-private-tcp-active-active/google-private-tcp-active-active-replicated/
      private_test: true

  standalone_external_rhel8_worker_replicated:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/google-tests.yml@ah/tf-8611-gcp-fdo-3
    secrets: inherit
    name: Standalone External Rhel8 Worker
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'standalone-external-rhel8-worker-replicated'}}
    with:
      test_name: Standalone External Rhel8 Worker
      module_repository_id: hashicorp/terraform-google-terraform-enterprise
      work_dir: ./tests/standalone-external-rhel8-worker
      k6_work_dir: ./tests/tfe-load-test
      private_test: false
      utility_test: false
      is_replicated_deployment: true
      enable_iact_subnet_list: false
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      TFC_token_secret_name: STANDALONE_EXTERNAL_RHEL8_WORKER_REPLICATED_TFC_TOKEN
      TFC_workspace_substitution_pattern: 's/terraform {/terraform {\n\
        backend "remote" {\n\
          organization = "terraform-enterprise-modules-test"\n\
          workspaces {\n\
            name = "google-standalone-external-rhel8-worker-replicated"\n\
          }\n\
        }\n/'

  standalone_mounted_disk_replicated:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/google-tests.yml@ah/tf-8611-gcp-fdo-3
    secrets: inherit
    name: Standalone Mounted Disk
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'standalone-mounted-disk-replicated' }}
    with:
      test_name: Standalone Mounted Disk
      module_repository_id: hashicorp/terraform-google-terraform-enterprise
      work_dir: ./tests/standalone-mounted-disk
      k6_work_dir: ./tests/tfe-load-test
      utility_test: false
      is_replicated_deployment: true
      private_test: false
      enable_iact_subnet_list: false
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      TFC_token_secret_name: STANDALONE_MOUNTED_DISK_REPLICATED_TFC_TOKEN
      TFC_workspace_substitution_pattern: 's/terraform {/terraform {\n\
        backend "remote" {\n\
          organization = "terraform-enterprise-modules-test"\n\
          workspaces {\n\
            name = "google-standalone-mounted-disk-replicated"\n\
          }\n\
        }\n/'
